<?xml version="1.0" encoding="utf-8"?><Database Name="mydb" Class="DCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=mydb;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="mydbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admin">
    <Type Name="Admin">
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pwd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Goods" Member="Goods">
    <Type Name="Goods">
      <Column Name="gid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="gtype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gprice" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGoods" Member="UserGoods">
    <Type Name="UserGoods">
      <Column Name="uid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gtype" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="gprice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="gstatus" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Users_UserGoods" Member="Users" ThisKey="uid" OtherKey="uid" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="uid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="uname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="usex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="upwd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="uschool" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Users_UserGoods" Member="UserGoods" ThisKey="uid" OtherKey="uid" Type="UserGoods" />
    </Type>
  </Table>
</Database>